apiVersion: 1

contactPoints:
  - orgId: 1
    name: webhook
    receivers:
      - uid: webhook-receiver
        type: webhook
        settings:
          # Replace this URL — same one as in alertmanager/alertmanager.yml
          # Use webhook.site, Discord, or Slack webhook URL
          url: https://webhook.site/24e90dd5-843e-4ec5-ae87-f390930dbdda
          httpMethod: POST
        disableResolveMessage: false
